### ISSUE TITLE
Spell Suggestion

### ISSUE THREAD

**Issue by dev-saw99** [SONUKUMARSAW/WordProcessor#1]
We need to implement an algorithm for spelling suggestions, for all the incorrect words displayed in the error box.

**Comment by satanb4** [comment]
Please assign this issue to me for now. As this is critical

**Comment by dev-saw99** [comment]
Any progress on the issue?

**Comment by satanb4** [comment]
Working on it. Will submit PR for review when done

**Comment by satanb4** [comment]
@SONUKUMARSAW This issue has been addressed. Please review and merge. If any issues, let me know
