### ISSUE TITLE
Add to dictionary

### ISSUE THREAD

**Issue by dev-saw99** [SONUKUMARSAW/WordProcessor#3]
Add new words to the dictionary.
If the user wants to add the particular word in the dictionary for further uses.

**Comment by satanb4** [comment]
Hi, I went through all the issues in the program. I'll start by addressing the most critical ones first. Please mark the issues which are the most critical as of now. Feature development can be done after that is resolved.

Also, a suggestion, to add 'requirements.txt' for controlling the dependencies for the user.

**Comment by dev-saw99** [comment]
> Hi, I went through all the issues in the program. I'll start by addressing the most critical ones first. Please mark the issues which are the most critical as of now. Feature development can be done after that is resolved.
> 
> Also, a suggestion, to add 'requirements.txt' for controlling the dependencies for the user.

Hey, @satanb4 thanks for showing interest in the project, The most critical issue in the project is spelling suggestion. I tried nltk.edit_distance() and nltk.jaccad_distance()  but it didn't work well.

And thanks for the suggestion of requirements.txt, I will add it by tonight.

**Comment by satanb4** [comment]
I'll start work on the spelling suggestion. Assign me the issue so that I can keep a track of it and log it as well. Also will be updating the README.

**Comment by dev-saw99** [comment]
> I'll start work on the spelling suggestion. Assign me the issue so that I can keep a track of it and log it as well. Also will be updating the README.

Please do comment in issue no 1 so that I assign you that issue.

**Comment by satanb4** [comment]
Will start working on this issue now.
